# 配置文件

DAILY_TIME: "10:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2023-12-26" # 纪念日
CITY: "广州"

BIRTHDAY:
  - "12-09"

APP_ID: "wx1d96083a2a8eb17b"
APP_SECRET: "4eb7dbe3e3552afc6e7f080ed73145ed"

USER_ID: 
  - "oFoL17EIwAPDak13BuAiecVNbce4"
  - "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "MEVdmM0VKDW-WlYVarxscRA0YDDfZTKWNyy8fR2vJ0I"
